=== nuritaiswati18/tugas-week3/schemas/search-user-by-id-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "firstName": {
        "type": "string"
      },
      "lastName": {
        "type": "string"
      },
      "age": {
        "type": "integer"
      },
      "occupation": {
        "type": "string"
      },
      "nationality": {
        "type": "string"
      },
      "hobbies": {
        "type": "array",
        "items": [
          {
            "type": "string"
          }
        ]
      },
      "gender": {
        "type": "string"
      },
      "createdDate": {
        "type": "string"
      },
      "updatedDate": {
        "type": ["string", "null"]
      }
    },
    "required": [
      "id",
      "firstName",
      "lastName",
      "age",
      "occupation",
      "nationality",
      "hobbies",
      "gender",
      "createdDate",
      "updatedDate"
    ]
  }

=== nuritaiswati18/tugas-week3/data/update-user-positive.json
{
    "id": "3d9f72e4-94dc-47ee-ade7-4b8315939139",
    "firstName": "kakak",
    "lastName": "adik",
    "age": 30,
    "occupation": "software developer",
    "nationality": "singapore",
    "hobbies": ["reading book"],
    "gender": "MALE",
    "createdDate": "2022-08-10T08:08:36.019Z",
    "updatedDate": "2022-08-10T08:08:36.019Z"
  }
